
import type { Author, Book, Review, Category } from './types';

const authors: Author[] = [
  { id: '1', name: 'F. Scott Fitzgerald' },
  { id: '2', name: 'George Orwell' },
  { id: '3', name: 'Harper Lee' },
  { id: '4', name: 'J.D. Salinger' },
  { id: '5', name: 'Jane Austen' },
  { id: '6', name: 'J.R.R. Tolkien' },
  { id: '7', name: 'Herman Melville'},
  { id: '8', name: 'Leo Tolstoy'},
  { id: '9', name: 'William Shakespeare'},
  { id: '10', name: 'Charles Dickens'},
  { id: '11', name: 'Homer'},
  { id: '12', name: 'Aldous Huxley'},
  { id: '13', name: 'Mary Shelley' },
  { id: '14', name: 'Bram Stoker' },
  { id: '15', name: 'Mark Twain' },
  { id: '16', name: 'Fyodor Dostoevsky' },
  { id: '17', name: 'Virginia Woolf' },
  { id: '18', name: 'Agatha Christie' },
  { id: '19', name: 'Arthur Conan Doyle' },
  { id: '20', name: 'Jules Verne' },
  { id: '21', name: 'Oscar Wilde' },
  { id: '22', name: 'Edgar Allan Poe' },
  { id: '23',name: 'Emily Brontë' },
  { id: '24', name: 'Charlotte Brontë' },
];

const reviews: Review[] = [
  {
    id: '1',
    bookId: '1',
    userId: '1',
    userName: 'Jane Doe',
    userAvatar: 'user-1',
    rating: 5,
    comment: "A timeless classic that perfectly captures the Jazz Age. Fitzgerald's writing is simply sublime.",
    createdAt: '2023-10-15',
  },
  {
    id: '2',
    bookId: '1',
    userId: '2',
    userName: 'John Smith',
    userAvatar: 'user-2',
    rating: 4,
    comment: 'An engaging read, though the characters can be frustrating. A must-read for any literature enthusiast.',
    createdAt: '2023-10-12',
  },
  {
    id: '3',
    bookId: '2',
    userId: '1',
    userName: 'Jane Doe',
    userAvatar: 'user-1',
    rating: 5,
    comment: "Orwell's dystopian vision is more relevant than ever. A chilling and thought-provoking masterpiece.",
    createdAt: '2023-09-20',
  },
];

const books: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: authors[0],
    genre: 'Classic',
    price: 999.00,
    stock: 50,
    description: "The Great Gatsby, F. Scott Fitzgerald's third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers.",
    rating: 4.5,
    coverImage: 'book-1',
    reviews: reviews.filter(r => r.bookId === '1'),
  },
  {
    id: '2',
    title: '1984',
    author: authors[1],
    genre: 'Dystopian',
    price: 899.00,
    stock: 30,
    description: "George Orwell's Nineteen Eighty-Four is a dystopian social science fiction novel and cautionary tale. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime.",
    rating: 4.8,
    coverImage: 'book-2',
    reviews: reviews.filter(r => r.bookId === '2'),
  },
  {
    id: '3',
    title: 'To Kill a Mockingbird',
    author: authors[2],
    genre: 'Classic',
    price: 1199.00,
    stock: 25,
    description: "To Kill a Mockingbird is a novel by Harper Lee published in 1960. Instantly successful, widely read in high schools and middle schools in the United States, it has become a classic of modern American literature, winning the Pulitzer Prize.",
    rating: 4.7,
    coverImage: 'book-3',
    reviews: [],
  },
  {
    id: '4',
    title: 'The Catcher in the Rye',
    author: authors[3],
    genre: 'Classic',
    price: 799.00,
    stock: 40,
    description: "The Catcher in the Rye is a novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951. It was originally intended for adults but is often read by adolescents for its themes of angst and alienation.",
    rating: 4.2,
    coverImage: 'book-4',
    reviews: [],
  },
  {
    id: '5',
    title: 'Pride and Prejudice',
    author: authors[4],
    genre: 'Romance',
    price: 949.00,
    stock: 60,
    description: "Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments.",
    rating: 4.9,
    coverImage: 'book-5',
    reviews: [],
  },
  {
    id: '6',
    title: 'The Hobbit',
    author: authors[5],
    genre: 'Fantasy',
    price: 1499.00,
    stock: 75,
    description: "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune.",
    rating: 4.9,
    coverImage: 'book-6',
    reviews: [],
  },
  {
    id: '7',
    title: 'Moby Dick',
    author: authors[6],
    genre: 'Adventure',
    price: 1250.00,
    stock: 10,
    description: 'The narrative of the sailor Ishmael and his voyage on the whaleship Pequod, commanded by Captain Ahab.',
    rating: 4.1,
    coverImage: 'book-7',
    reviews: [],
  },
  {
    id: '8',
    title: 'War and Peace',
    author: authors[7],
    genre: 'Historical Fiction',
    price: 1800.00,
    stock: 15,
    description: 'A literary work mixed with chapters on history and philosophy, it chronicles the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the stories of five Russian aristocratic families.',
    rating: 4.6,
    coverImage: 'book-8',
    reviews: [],
  },
  {
    id: '9',
    title: 'Hamlet',
    author: authors[8],
    genre: 'Tragedy',
    price: 699.00,
    stock: 35,
    description: 'The tragedy of Hamlet, Prince of Denmark, is a tragedy play by William Shakespeare believed to have been written between 1599 and 1601.',
    rating: 4.7,
    coverImage: 'book-9',
    reviews: [],
  },
  {
    id: '10',
    title: 'Great Expectations',
    author: authors[9],
    genre: 'Classic',
    price: 850.00,
    stock: 20,
    description: 'Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel. It depicts the education of an orphan nicknamed Pip.',
    rating: 4.4,
    coverImage: 'book-10',
    reviews: [],
  },
  {
    id: '11',
    title: 'The Odyssey',
    author: authors[10],
    genre: 'Epic',
    price: 1100.00,
    stock: 18,
    description: 'The Odyssey is one of two major ancient Greek epic poems attributed to Homer. It is, in part, a sequel to the Iliad, the other work ascribed to Homer.',
    rating: 4.8,
    coverImage: 'book-11',
    reviews: [],
  },
  {
    id: '12',
    title: 'Brave New World',
    author: authors[11],
    genre: 'Dystopian',
    price: 950.00,
    stock: 45,
    description: 'Brave New World is a dystopian social science fiction novel by English author Aldous Huxley, written in 1931 and published in 1932.',
    rating: 4.6,
    coverImage: 'book-12',
    reviews: [],
  },
  {
    id: '13',
    title: 'Frankenstein',
    author: authors[12],
    genre: 'Gothic Fiction',
    price: 750.00,
    stock: 33,
    description: 'Frankenstein; or, The Modern Prometheus is a novel written by English author Mary Shelley that tells the story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment.',
    rating: 4.5,
    coverImage: 'book-13',
    reviews: [],
  },
  {
    id: '14',
    title: 'Dracula',
    author: authors[13],
    genre: 'Gothic Fiction',
    price: 820.00,
    stock: 28,
    description: 'Dracula is a novel by Bram Stoker, published in 1897. It is an epistolary novel, meaning it is told through letters, diary entries, and newspaper articles.',
    rating: 4.6,
    coverImage: 'book-14',
    reviews: [],
  },
  {
    id: '15',
    title: 'The Adventures of Tom Sawyer',
    author: authors[14],
    genre: 'Adventure',
    price: 650.00,
    stock: 55,
    description: 'The Adventures of Tom Sawyer by Mark Twain is an 1876 novel about a young boy growing up along the Mississippi River.',
    rating: 4.3,
    coverImage: 'book-15',
    reviews: [],
  },
  {
    id: '16',
    title: 'Crime and Punishment',
    author: authors[15],
    genre: 'Philosophical Fiction',
    price: 1150.00,
    stock: 22,
    description: 'Crime and Punishment is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866.',
    rating: 4.8,
    coverImage: 'book-16',
    reviews: [],
  },
  {
    id: '17',
    title: 'Mrs Dalloway',
    author: authors[16],
    genre: 'Modernist',
    price: 980.00,
    stock: 19,
    description: 'Mrs Dalloway is a novel by Virginia Woolf that details a day in the life of Clarissa Dalloway, a fictional high-society woman in post-First World War England.',
    rating: 4.2,
    coverImage: 'book-17',
    reviews: [],
  },
  {
    id: '18',
    title: 'And Then There Were None',
    author: authors[17],
    genre: 'Mystery',
    price: 890.00,
    stock: 60,
    description: 'And Then There Were None is a mystery novel by the English writer Agatha Christie, her best-selling novel and the world\'s best-selling mystery.',
    rating: 4.7,
    coverImage: 'book-18',
    reviews: [],
  },
  {
    id: '19',
    title: 'A Study in Scarlet',
    author: authors[18],
    genre: 'Mystery',
    price: 720.00,
    stock: 40,
    description: 'A Study in Scarlet is an 1887 detective novel by British author Arthur Conan Doyle. The story marks the first appearance of Sherlock Holmes and Dr. Watson, who would become two of the most famous characters in popular fiction.',
    rating: 4.6,
    coverImage: 'book-19',
    reviews: [],
  },
  {
    id: '20',
    title: 'Journey to the Center of the Earth',
    author: authors[19],
    genre: 'Adventure',
    price: 1050.00,
    stock: 38,
    description: 'A classic science fiction novel by Jules Verne. The story involves German professor Otto Lidenbrock who believes there are volcanic tubes going toward the centre of the Earth.',
    rating: 4.4,
    coverImage: 'book-20',
    reviews: [],
  },
  {
    id: '21',
    title: 'The Picture of Dorian Gray',
    author: authors[20],
    genre: 'Philosophical Fiction',
    price: 880.00,
    stock: 25,
    description: 'The Picture of Dorian Gray is a philosophical novel by Oscar Wilde. A story of a young man who sells his soul for eternal youth and beauty.',
    rating: 4.5,
    coverImage: 'book-21',
    reviews: [],
  },
  {
    id: '22',
    title: 'The Raven',
    author: authors[21],
    genre: 'Poetry',
    price: 550.00,
    stock: 50,
    description: 'A narrative poem by American writer Edgar Allan Poe. First published in January 1845, the poem is often noted for its musicality, stylized language, and supernatural atmosphere.',
    rating: 4.7,
    coverImage: 'book-22',
    reviews: [],
  },
  {
    id: '23',
    title: 'Wuthering Heights',
    author: authors[22],
    genre: 'Gothic Fiction',
    price: 920.00,
    stock: 31,
    description: 'Wuthering Heights is Emily Brontë\'s only novel. It was first published in 1847 under the pseudonym "Ellis Bell", and a posthumous second edition was edited by her sister Charlotte.',
    rating: 4.4,
    coverImage: 'book-23',
    reviews: [],
  },
  {
    id: '24',
    title: 'Jane Eyre',
    author: authors[23],
    genre: 'Romance',
    price: 960.00,
    stock: 42,
    description: 'Jane Eyre is a novel by English writer Charlotte Brontë, published under the pen name "Currer Bell", on 16 October 1847.',
    rating: 4.6,
    coverImage: 'book-24',
    reviews: [],
  },
  {
    id: '25',
    title: 'Anna Karenina',
    author: authors[7],
    genre: 'Realist Novel',
    price: 1250.00,
    stock: 20,
    description: 'Anna Karenina is a novel by the Russian author Leo Tolstoy, first published in book form in 1878. Many authors consider it to be one of the greatest works of literature ever written.',
    rating: 4.8,
    coverImage: 'book-25',
    reviews: [],
  },
  {
    id: '26',
    title: 'The Brothers Karamazov',
    author: authors[15],
    genre: 'Philosophical Fiction',
    price: 1300.00,
    stock: 18,
    description: 'The Brothers Karamazov is the final novel by the Russian author Fyodor Dostoevsky. Dostoevsky spent nearly two years writing The Brothers Karamazov, which was published as a serial in The Russian Messenger from January 1879 to November 1880.',
    rating: 4.9,
    coverImage: 'book-26',
    reviews: [],
  },
  {
    id: '27',
    title: 'Don Quixote',
    author: { id: '25', name: 'Miguel de Cervantes' },
    genre: 'Satire',
    price: 1100.00,
    stock: 25,
    description: 'The Ingenious Gentleman Don Quixote of La Mancha, or just Don Quixote, is a Spanish novel by Miguel de Cervantes. Published in two parts, in 1605 and 1615, it is the most influential work of literature from the Spanish Golden Age.',
    rating: 4.7,
    coverImage: 'book-27',
    reviews: [],
  },
  {
    id: '28',
    title: 'One Hundred Years of Solitude',
    author: { id: '26', name: 'Gabriel García Márquez' },
    genre: 'Magical Realism',
    price: 1050.00,
    stock: 30,
    description: 'One Hundred Years of Solitude is a 1967 novel by Colombian author Gabriel García Márquez that tells the multi-generational story of the Buendía family, whose patriarch, José Arcadio Buendía, founded the town of Macondo.',
    rating: 4.6,
    coverImage: 'book-28',
    reviews: [],
  },
  {
    id: '29',
    title: 'The Lord of the Rings',
    author: authors[5],
    genre: 'Fantasy',
    price: 2500.00,
    stock: 50,
    description: 'The Lord of the Rings is an epic high-fantasy novel by the English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien\'s 1937 children\'s book The Hobbit, but eventually developed into a much larger work.',
    rating: 4.9,
    coverImage: 'book-29',
    reviews: [],
  },
  {
    id: '30',
    title: 'The Divine Comedy',
    author: { id: '27', name: 'Dante Alighieri' },
    genre: 'Epic',
    price: 1400.00,
    stock: 22,
    description: 'The Divine Comedy is a long Italian narrative poem by Dante Alighieri, begun c. 1308 and completed in 1320, a year before his death in 1321. It is widely considered to be the pre-eminent work in Italian literature and one of the greatest works of world literature.',
    rating: 4.8,
    coverImage: 'book-30',
    reviews: [],
  }
];

const categories: Category[] = [
    { id: '1', name: 'Classic' },
    { id: '2', name: 'Dystopian' },
    { id: '3', name: 'Romance' },
    { id: '4', name: 'Fantasy' },
    { id: '5', name: 'Adventure' },
    { id: '6', name: 'Historical Fiction' },
    { id: '7', name: 'Tragedy' },
    { id: '8', name: 'Epic' },
    { id: '9', name: 'Gothic Fiction' },
    { id: '10', name: 'Philosophical Fiction' },
    { id: '11', name: 'Modernist' },
    { id: '12', name: 'Mystery' },
    { id: '13', name: 'Poetry' },
    { id: '14', name: 'Realist Novel' },
    { id: '15', name: 'Satire' },
    { id: '16', name: 'Magical Realism' },
]

export function getBooks() {
  return books;
}

export function getBookById(id: string) {
  return books.find(book => book.id === id);
}

export function getFeaturedBooks() {
  return books.slice(0, 4);
}

export function getAuthors() {
    return authors;
}

export function getCategories() {
    return categories;
}
